# Action runs jobs automatically when the events defined below are triggered by github.

# This action checks the commits that were pushed with the pull request
name: Lint Commits

on:
  # The jobs defined below would be triggered everytime there is a pull request on this repository
  pull_request:

jobs:
  # This job runs the linter
  lint:
    # It runs on the latest version of ubuntu
    runs-on: ubuntu-latest
    # These are the steps for the job
    steps:
      # this step uses the checkout action to checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # fetch-depth defines the number of commits to fetch.
          # 0 indicates all history for all branches and tags.
          fetch-depth: 0
      # Lints Pull Request commits with commitlint
      - name: Commit linter
        uses: wagoid/commitlint-github-action@v5
